name: 'Build and deploy to dev'

on:
  workflow_dispatch:
  push:
    branches:
#      - main
      - develop
    paths-ignore:
      - '.*'
      - '!.dockerignore'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'Makefile'
      - '.github/'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  compile-and-test:
#    uses: ./.github/workflows/pr-develop.yaml

  build-push-image:
#    needs: compile-and-test
#    if: |
#      github.ref_name == 'develop'
    uses: ./.github/workflows/docker.yaml


#
#
#Develop  -> release 1.0.0
#Develop <- release 1.0.0
#Image 1.0.0.10
#
#Release 1.0.0 -> master
#Master <- release 1.0.0
#Image 1.0.0
#Creates tag -> release out of tag with changeling
#
#In case of bug
#
#Master -> hotfix/1.0.1
#Master <- hotfix/1.0.1
#Image 1.0.1
#
#Image jest na stage I potem prod
#Creates tag -> release out of tag with changelist
#
#Develop <- hotfix/1.0.1
#Image 1.0.1.11
#
#
#
#