name: 'Build and deploy to dev'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.*'
      - '!.dockerignore'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'Makefile'
      - '.github/'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-and-test:
    uses: ./.github/workflows/feature.yaml

  build-push-image:
    needs: compile-and-test
    if: |
      github.ref_name == 'develop'
    uses: ./.github/workflows/docker.yaml